// interfaces/payment.interface.ts

import { ObjectId } from "mongoose";

export interface ISubscription {
  _id?: string; // Optional, as it will be generated by MongoDB
  created: ObjectId;
  name: string;
  price: number;
  duration: number;
  features?: string[],
  isDeleted?: boolean
}
