// interfaces/payment.interface.ts

import { ObjectId } from "mongoose";

export const durationTypes =["Each","Video","Day", "Week", "Month", "Year"] as const;

export type durationType = typeof durationTypes[number];

export const subscriptionType = ['essentialVisibility', 'starterDiscovery', 'enhancedPresence', 'premiumPartner', 'premiumPlus', 'smartExpansion', "smartCorporate", "corporatePrestige", "pushNotification", "promoVideoOnProfile", "homepageVideo", "featuredTodayBanner", "top5OfTheWeekBadge"] as const;


export interface ISubscription {
  _id?: string; // Optional, as it will be generated by MongoDB
  created: ObjectId;
  name: string;
  description?: string;
  price: number;
  duration: number;
  durationType: durationType,
  type: string;
  features?: string[];
  restrictionFeatures?: string[];
  lastDescription?: string;
  isDeleted?: boolean
}
